### ISSUE TITLE
Error when run the built program

### ISSUE THREAD

**Issue by J-F-Liu** [snuk182/nuklear-test#3] opened 2017-05-04 01:08 UTC
`cargo run` works, but there is error when run the program manually after `cargo build`.
```
▶ RUST_BACKTRACE=1 ./t
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', /checkout/src/libcore/result.rs:859
stack backtrace:
   0: std::sys::imp::backtrace::tracing::imp::unwind_backtrace
             at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::_print
             at /checkout/src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at /checkout/src/libstd/sys_common/backtrace.rs:60
             at /checkout/src/libstd/panicking.rs:355
   3: std::panicking::default_hook
             at /checkout/src/libstd/panicking.rs:371
   4: std::panicking::rust_panic_with_hook
             at /checkout/src/libstd/panicking.rs:549
   5: std::panicking::begin_panic
             at /checkout/src/libstd/panicking.rs:511
   6: std::panicking::begin_panic_fmt
             at /checkout/src/libstd/panicking.rs:495
   7: rust_begin_unwind
             at /checkout/src/libstd/panicking.rs:471
   8: core::panicking::panic_fmt
             at /checkout/src/libcore/panicking.rs:69
   9: core::result::unwrap_failed
             at /checkout/src/libcore/macros.rs:29
  10: <core::result::Result<T, E>>::unwrap
             at /checkout/src/libcore/result.rs:737
  11: t::icon_load
             at src/main.rs:88
  12: t::main
             at src/main.rs:160
  13: __rust_maybe_catch_panic
             at /checkout/src/libpanic_unwind/lib.rs:98
  14: std::rt::lang_start
             at /checkout/src/libstd/panicking.rs:433
             at /checkout/src/libstd/panic.rs:361
             at /checkout/src/libstd/rt.rs:57
  15: main
  16: __libc_start_main
  17: _start
```

**Comment by snuk182** [comment] 2017-05-05 12:22
Hi, could you please share your system name and version (I see it is something unix-looked) and rust and cargo versions?

**Comment by J-F-Liu** [comment] 2017-05-06 14:59
The error relates to current work directory.
```
nuklear-test/target/debug
▶ ./t
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Os { code: 2, message: "No such file or directory" } }', /checkout/src/libcore/result.rs:859
note: Run with `RUST_BACKTRACE=1` for a backtrace.

nuklear-test/target/debug
▶ cd ../..

~/SourceCode/nuklear-test
▶ ./target/debug/t

~/SourceCode/nuklear-test
▶rustc -V
rustc 1.19.0-nightly (06fb4d256 2017-04-30)

~/SourceCode/nuklear-test
▶ cargo -V
cargo 0.19.0-nightly (fa7584c14 2017-04-26)
▶ uname -r
4.10.13-1-ARCH
```

**Comment by rminderhoud** [comment] 2018-03-06 17:28
Most likely due to trying to load resources from `res/` directory. Probably expected behaviour and if this wasn't just an example you would try to catch that error. I think probably worth closing this issue or adding a note to the README

**Comment by snuk182** [comment] 2018-09-10 11:01
Close so far. Feel free to reopen if the resources access problems get back.

**Closed as completed by snuk182** 2018-09-10 11:01 UTC
